var level2 = {
    "map_height": 11243,
    "map_width": 670,
    "map_path": "level.png",
    "increase_speed_point": -5000,
    "decrease_speed_point": -9900,
    "level_id": "2",
    "elements_drew": [
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 127,
            "y": 278,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 487,
            "y": 397,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 224,
            "y": 310,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 324,
            "y": 342,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 504,
            "y": 535,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 405,
            "y": 567,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 315,
            "y": 598,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 121,
            "y": 1460,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 217,
            "y": 1492,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 318,
            "y": 1524,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 510,
            "y": 1710,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 419,
            "y": 1742,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 318,
            "y": 1780,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 122,
            "y": 1972,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 326,
            "y": 2037,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 230,
            "y": 1998,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 505,
            "y": 2227,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 311,
            "y": 2291,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 404,
            "y": 2259,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 133,
            "y": 2483,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 231,
            "y": 2515,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 318,
            "y": 2547,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 504,
            "y": 2739,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 312,
            "y": 2803,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 415,
            "y": 2765,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 129,
            "y": 2995,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 217,
            "y": 3026,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 315,
            "y": 3058,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 505,
            "y": 3250,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 319,
            "y": 3313,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 416,
            "y": 3276,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 317,
            "y": 3568,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 126,
            "y": 3504,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 228,
            "y": 3536,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 505,
            "y": 3760,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 311,
            "y": 3824,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 417,
            "y": 3792,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 129,
            "y": 4016,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 325,
            "y": 4080,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 226,
            "y": 4042,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 506,
            "y": 4272,
            "alive": true
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 319,
            "y": 4336,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 413,
            "y": 4298,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 312,
            "y": 4848,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 408,
            "y": 4816,
            "alive": true
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 502,
            "y": 4784,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 138,
            "y": 5527,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 114,
            "y": 9323,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 506,
            "y": 9237,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 325,
            "y": 9293,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 148,
            "y": 9104,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 410,
            "y": 8997,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 456,
            "y": 9113,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 154,
            "y": 8829,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 502,
            "y": 8753,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 171,
            "y": 8538,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 474,
            "y": 8327,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 180,
            "y": 8223,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 495,
            "y": 8186,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 164,
            "y": 8387,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 515,
            "y": 8448,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 186,
            "y": 8735,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 517,
            "y": 8816,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 165,
            "y": 8985,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 442,
            "y": 8626,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 127,
            "y": 8004,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 499,
            "y": 7859,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 118,
            "y": 7695,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 491,
            "y": 7336,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 126,
            "y": 7492,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 495,
            "y": 7516,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 127,
            "y": 7101,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 137,
            "y": 7381,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 512,
            "y": 7437,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 406,
            "y": 7604,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 157,
            "y": 7580,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 531,
            "y": 7778,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 157,
            "y": 7810,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 383,
            "y": 7949,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 141,
            "y": 8135,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 540,
            "y": 7986,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 160,
            "y": 7251,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 488,
            "y": 6946,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 126,
            "y": 6819,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 495,
            "y": 6864,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 511,
            "y": 7111,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 211,
            "y": 6938,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 488,
            "y": 6590,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 136,
            "y": 6489,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 109,
            "y": 5668,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 147,
            "y": 5668,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 185,
            "y": 5668,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 224,
            "y": 5668,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 360,
            "y": 5665,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 401,
            "y": 5664,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 443,
            "y": 5664,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 507,
            "y": 5666,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 553,
            "y": 5665,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 262,
            "y": 5794,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 534,
            "y": 5742,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 504,
            "y": 5917,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 500,
            "y": 6313,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 148,
            "y": 5965,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 174,
            "y": 6283,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 518,
            "y": 6097,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 130,
            "y": 6100,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 524,
            "y": 6202,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 124,
            "y": 6188,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 213,
            "y": 6685,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 460,
            "y": 6028,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 325,
            "y": 6176,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 370,
            "y": 5896,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 350,
            "y": 6521,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 385,
            "y": 6803,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 325,
            "y": 7260,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 333,
            "y": 7075,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 318,
            "y": 7758,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 327,
            "y": 7460,
            "alive": true
        },
        {
            "name": "death-star",
            "path": "graphics/death-star",
            "width": 69,
            "height": 66,
            "frames": 2,
            "accual_frame": 1,
            "x": 304,
            "y": 11052,
            "alive": true
        }
    ],
    "speed": "1",
    "increased_speed": "1"
}