var level1 = {
    "map_height": 11243,
    "map_width": 670,
    "map_path": "level.png",
    "increase_speed_point": -5000,
    "decrease_speed_point": -9900,
    "level_id": "1",
    "elements_drew": [
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 126,
            "y": 279,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 227,
            "y": 311,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 330,
            "y": 337,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 505,
            "y": 535,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 408,
            "y": 568,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 320,
            "y": 599,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 123,
            "y": 1461,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 220,
            "y": 1493,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 325,
            "y": 1519,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 501,
            "y": 1717,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 409,
            "y": 1749,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 322,
            "y": 1781,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 125,
            "y": 1973,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 232,
            "y": 1999,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 325,
            "y": 2036,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 503,
            "y": 2228,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 405,
            "y": 2260,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 319,
            "y": 2292,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 125,
            "y": 2484,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 230,
            "y": 2516,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 315,
            "y": 2548,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 503,
            "y": 2740,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 408,
            "y": 2772,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 307,
            "y": 2804,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 134,
            "y": 2989,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 232,
            "y": 3021,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 320,
            "y": 3053,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 500,
            "y": 3250,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 406,
            "y": 3282,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 309,
            "y": 3314,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 133,
            "y": 3505,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 224,
            "y": 3537,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 316,
            "y": 3569,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 515,
            "y": 3755,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 408,
            "y": 3793,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 310,
            "y": 3825,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 128,
            "y": 4017,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 228,
            "y": 4049,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 317,
            "y": 4081,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 505,
            "y": 4273,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 411,
            "y": 4305,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 308,
            "y": 4337,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 503,
            "y": 4785,
            "alive": true,
        },
        {
            "name": "fuel",
            "path": "graphics/fuel",
            "width": 48,
            "height": 32,
            "frames": 2,
            "accual_frame": 1,
            "x": 407,
            "y": 4817,
            "alive": true,
        },
        {
            "name": "mushroom",
            "path": "graphics/mushroom",
            "width": 34,
            "height": 30,
            "frames": 4,
            "accual_frame": 1,
            "x": 317,
            "y": 4849,
            "alive": true,
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 138,
            "y": 5835,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 114,
            "y": 9920,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 475,
            "y": 9949,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 464,
            "y": 5923,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 415,
            "y": 6081,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 122,
            "y": 6011,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 363,
            "y": 6272,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 433,
            "y": 6006,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 162,
            "y": 6219,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 330,
            "y": 6153,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 158,
            "y": 6414,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 479,
            "y": 6521,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 503,
            "y": 6347,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 515,
            "y": 6171,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 162,
            "y": 6567,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 370,
            "y": 6439,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 414,
            "y": 9775,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 176,
            "y": 9440,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 157,
            "y": 9800,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 352,
            "y": 9556,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 468,
            "y": 9187,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 503,
            "y": 9276,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 110,
            "y": 9149,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 445,
            "y": 8992,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 407,
            "y": 8747,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 472,
            "y": 8534,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 126,
            "y": 8637,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 149,
            "y": 8906,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 408,
            "y": 8264,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 137,
            "y": 8388,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 384,
            "y": 6770,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 163,
            "y": 6992,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 507,
            "y": 7032,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 437,
            "y": 7314,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 500,
            "y": 7656,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 462,
            "y": 7977,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 158,
            "y": 8210,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 152,
            "y": 7823,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 194,
            "y": 7531,
            "alive": true
        },
        {
            "name": "fuel-ship",
            "path": "graphics/fuel-ship",
            "width": 56,
            "height": 30,
            "frames": 2,
            "accual_frame": 1,
            "x": 197,
            "y": 7238,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 503,
            "y": 6661,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 472,
            "y": 6942,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 136,
            "y": 6869,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 375,
            "y": 7139,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 213,
            "y": 6713,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 462,
            "y": 7539,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 236,
            "y": 7413,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 164,
            "y": 7689,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 358,
            "y": 7766,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 150,
            "y": 7985,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 483,
            "y": 8170,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 340,
            "y": 8076,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 484,
            "y": 7873,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 485,
            "y": 8405,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 230,
            "y": 8517,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 506,
            "y": 8668,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 521,
            "y": 8848,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 196,
            "y": 8780,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 252,
            "y": 8988,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 171,
            "y": 9307,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 499,
            "y": 9467,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 166,
            "y": 9685,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 206,
            "y": 9549,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 363,
            "y": 9369,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 283,
            "y": 9160,
            "alive": true
        },
        {
            "name": "enemy-ship-stand",
            "path": "graphics/enemy-ship-stand",
            "width": 30,
            "height": 28,
            "frames": 2,
            "accual_frame": 1,
            "x": 316,
            "y": 8370,
            "alive": true
        },
        {
            "name": "death-star",
            "path": "graphics/death-star",
            "width": 69,
            "height": 66,
            "frames": 2,
            "accual_frame": 1,
            "x": 303,
            "y": 11052,
            "alive": true
        }
    ],
    "speed": "1",
    "increased_speed": "1"
}
